name: Publish npm package
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci-environment
      - name: Build package
        shell: bash
        run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
